# Generated by Django 2.2.12 on 2020-05-15 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField(verbose_name='Время начала занятий')),
                ('endTime', models.TimeField(verbose_name='Время окончания занятий')),
                ('weekDay', models.IntegerField(choices=[(1, 'понедельник'), (2, 'вторник'), (3, 'среда'), (4, 'четверг'), (5, 'пятница'), (6, 'субота'), (7, 'воскресенье')], verbose_name='день недели')),
                ('pay', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Плата')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.Lesson', verbose_name='вид тренировки')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.Place', verbose_name='место проведения')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', verbose_name='тренер')),
            ],
            options={
                'verbose_name': 'групповая тренировка',
                'verbose_name_plural': 'групповые тренировки',
            },
        ),
    ]
