# Generated by Django 2.2.12 on 2020-05-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplesson',
            name='availability',
            field=models.PositiveIntegerField(default=0, verbose_name='Свободно мест'),
        ),
    ]
